package movies;

public class MoviesArray {
    public static MoviesApplication[] findAll() {
        return new MoviesApplication[]{
                new MoviesApplication("Citizen Kane", "drama"),
                new MoviesApplication("Casablanca", "drama"),
                new MoviesApplication("The Godfather", "drama"),
                new MoviesApplication("Gone With The Wind", "drama"),
                new MoviesApplication("Lawrence Of Arabia", "drama"),
                new MoviesApplication("The Wizard Of Oz", "musical"),
                new MoviesApplication("The Graduate", "drama"),
                new MoviesApplication("On The Waterfront", "drama"),
                new MoviesApplication("Schindler's List", "drama"),
                new MoviesApplication("Singin' In The Rain", "musical"),
                new MoviesApplication("It's A Wonderful Life", "drama"),
                new MoviesApplication("Sunset Boulevard", "drama"),
                new MoviesApplication("The Bridge On The River Kwai", "drama"),
                new MoviesApplication("Some Like It Hot", "drama"),
                new MoviesApplication("Star Wars", "scifi"),
                new MoviesApplication("All About Eve", "drama"),
                new MoviesApplication("The African Queen", "drama"),
                new MoviesApplication("Psycho", "horror"),
                new MoviesApplication("Chinatown", "drama"),
                new MoviesApplication("One Flew Over The Cuckoo's Nest", "drama"),
                new MoviesApplication("The Grapes Of Wrath", "drama"),
                new MoviesApplication("2001: A Space Odyssey", "scifi"),
                new MoviesApplication("The Maltese Falcon", "drama"),
                new MoviesApplication("Raging Bull", "drama"),
                new MoviesApplication("E.T. The extra-terrestrial", "scifi"),
                new MoviesApplication("Dr. Strangelove", "drama"),
                new MoviesApplication("Bonnirre And Clyde", "drama"),
                new MoviesApplication("Apocalypse Now", "drama"),
                new MoviesApplication("Mr. Smith Goes to Washington", "drama"),
                new MoviesApplication("The Treasure Of The Sierra Madre", "drama"),
                new MoviesApplication("Annie Hall", "comedy"),
                new MoviesApplication("The Godfather Part II", "drama"),
                new MoviesApplication("High Noon", "drama"),
                new MoviesApplication("To Kill A Mockingbird", "drama"),
                new MoviesApplication("It Happened One Night", "drama"),
                new MoviesApplication("Midnight Cowboy", "drama"),
                new MoviesApplication("The Best Years Of Our Lives", "drama"),
                new MoviesApplication("Double Indemnity", "drama"),
                new MoviesApplication("Doctor Zhivago", "drama"),
                new MoviesApplication("North By Northwest", "drama"),
                new MoviesApplication("West Side Story", "musical"),
                new MoviesApplication("Rear Window", "drama"),
                new MoviesApplication("King Kong", "horror"),
                new MoviesApplication("The Birth Of A Nation", "drama"),
                new MoviesApplication("A Streetcar Named Desire", "drama"),
                new MoviesApplication("A Clockwork Orange", "scifi"),
                new MoviesApplication("Taxi Driver", "drama"),
                new MoviesApplication("Jaws", "horror"),
                new MoviesApplication("Snow White And The Seven Dwarfs", "animated"),
                new MoviesApplication("Butch Cassidy And The Sundance Kid", "drama"),
                new MoviesApplication("The Philadelphia Story", "drama"),
                new MoviesApplication("From Here To Eternity", "drama"),
                new MoviesApplication("Amadeus", "drama"),
                new MoviesApplication("All Quiet On The Western Front", "drama"),
                new MoviesApplication("The Sound Of Music", "musical"),
                new MoviesApplication("M*A*S*H", "comedy"),
                new MoviesApplication("The Third Man", "drama"),
                new MoviesApplication("Fantasia", "animated"),
                new MoviesApplication("Rebel Without A Cause", "drama"),
                new MoviesApplication("Raiders Of The Lost Ark", "drama"),
                new MoviesApplication("Vertigo", "drama"),
                new MoviesApplication("Tootsie", "comedy"),
                new MoviesApplication("Stagecoach", "drama"),
                new MoviesApplication("Close Encounters Of The Third Kind", "scifi"),
                new MoviesApplication("The Silence Of The Lambs", "horror"),
                new MoviesApplication("Network", "drama"),
                new MoviesApplication("The Manchurian Candidate", "drama"),
                new MoviesApplication("An American In Paris", "drama"),
                new MoviesApplication("Shane", "drama"),
                new MoviesApplication("The French Connection", "drama"),
                new MoviesApplication("Forrest Gump", "drama"),
                new MoviesApplication("Ben-Hur", "drama"),
                new MoviesApplication("Wuthering Heights", "drama"),
                new MoviesApplication("The Gold Rush", "drama"),
                new MoviesApplication("Dances With Wolves", "drama"),
                new MoviesApplication("City Lights", "drama"),
                new MoviesApplication("American Graffiti", "drama"),
                new MoviesApplication("Rocky", "drama"),
                new MoviesApplication("The Deer Hunter", "drama"),
                new MoviesApplication("The Wild Bunch", "drama"),
                new MoviesApplication("Modern Times", "drama"),
                new MoviesApplication("Giant", "drama"),
                new MoviesApplication("Platoon", "drama"),
                new MoviesApplication("Fargo", "drama"),
                new MoviesApplication("Duck Soup", "comedy"),
                new MoviesApplication("Mutiny On The Bounty", "drama"),
                new MoviesApplication("Frankenstein", "horror"),
                new MoviesApplication("Easy Rider", "drama"),
                new MoviesApplication("Patton", "drama"),
                new MoviesApplication("The Jazz Singer", "drama"),
                new MoviesApplication("My Fair Lady", "musical"),
                new MoviesApplication("A Place In The Sun", "drama"),
                new MoviesApplication("The Apartment", "drama"),
                new MoviesApplication("Goodfellas", "drama"),
                new MoviesApplication("Pulp Fiction", "drama"),
                new MoviesApplication("The Searchers", "drama"),
                new MoviesApplication("Bringing Up Baby", "drama"),
                new MoviesApplication("Unforgiven", "drama"),
                new MoviesApplication("Guess Who's Coming To Dinner", "drama"),
                new MoviesApplication("Yankee Doodle Dandy", "musical")
        };
    }
}
